version: '2.2'

x-logging:
  logging: &logging
    options:
      max-size: 50m

services:
  
  ctl:
    container_name: ctl
    hostname: ctl
    build: 
      context: ./
      args:
        CTL_IMAGE: ${CTL_IMAGE:-lucasbasquerotto/ansible}
        CTL_VERSION: ${CTL_VERSION:-0.0.2}
    environment:
    - DEV=0
    volumes:
    - .:/root/ctl:ro
    - ../vars:/root/vars:rw
    - ../r:/root/r:rw
    logging: *logging 
    command: sleep infinity
  
  ctl-dev:
    container_name: ctl-dev
    hostname: ctl-dev
    build: 
      context: ./
      args:
        CTL_IMAGE: ${CTL_IMAGE:-lucasbasquerotto/ansible}
        CTL_VERSION: ${CTL_VERSION:-0.0.2}
    environment:
    - DEV=1
    volumes:
    - .:/root/ctl:ro
    - ../vars:/root/vars:rw
    - ../r:/root/r:rw
    - ../cloud:/root/r/cloud:ro
    - ../env:/main/env:rw
    - ../cloud:/main/cloud:rw
    - ../pod:/main/pod:rw
    - ../app:/main/app:rw
    - ../data:/main/data:rw
    - ../data:/data:rw
    logging: *logging 
    command: sleep infinity