version: '3.4'

x-logging:
  logging: &logging
    options:
      max-size: 50m

services:
  
  ctl:
    container_name: ctl
    hostname: ctl
    build: 
      context: ./
    environment:
    - DEV=0
    volumes:
    - .:/root/ctl:ro
    - ../r:/root/r:rw
    logging: *logging 
    command: sleep infinity
  
  ctl-dev:
    container_name: ctl-dev
    hostname: ctl-dev
    build: 
      context: ./
    environment:
    - DEV=1
    volumes:
    - .:/root/ctl:ro
    - ../r:/root/r:rw
    - ../env:/main/env:rw
    - ../cloud:/main/cloud:rw
    - ../pod:/main/pod:rw
    - ../app:/main/app:rw
    - ../data:/data:rw
    logging: *logging 
    command: sleep infinity