version: '2.2'

x-logging:
  logging: &logging
    options:
      max-size: 50m

services:

  ctl:
    container_name: ctl
    hostname: ctl
    build:
      context: ./
      args:
        CTL_IMAGE: $CTL_IMAGE
        CTL_VERSION: $CTL_VERSION
    environment:
    - DEV=0
    volumes:
    - .:/root/ctl:ro
    - ./tmp/run:/root/run:rw
    - ../w:/root/w:rw
    - ../w/ctl/var:/root/var:rw
    logging: *logging
    command: sleep infinity

  ctl-dev:
    container_name: ctl-dev
    hostname: ctl-dev
    build:
      context: ./
      args:
        CTL_IMAGE: $CTL_IMAGE
        CTL_VERSION: $CTL_VERSION
    environment:
    - DEV=1
    volumes:
    - .:/root/ctl:ro
    - ./tmp/run:/root/run:rw
    - ../w/ctl/var:/root/var:rw
    - ../w:/root/w:rw
    - ../envs:/root/w/envs:ro
    - ../clouds:/root/w/clouds:ro
    - ../envs:/main/envs:rw
    - ../clouds:/main/clouds:rw
    - ../pods:/main/pods:rw
    - ../apps:/main/apps:rw
    - ../data:/main/data:rw
    - ../data:/data:rw
    - ../projects:/main/projects:rw
    logging: *logging
    command: sleep infinity