- name: Play 01 - Create Cloud Instances
  hosts: main
  vars_files:
  - "vars/main.yml"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: "update main repo"
    git:
      repo: "{{ main_repo }}"
      version: "{{ main_repo_version }}"
      dest: "{{ main_repo_dest }}"
      update: yes
    tags: ["main"]

  - include_tasks: "repo.yml"
