- name: Play 01 - Create and update the main and the environment repositories
  hosts: main
  vars_files:
  - "env/vars.yml"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 
    tags: ["other"]

  - name: "update main repo"
    git:
      repo: "{{ main_repo }}"
      version: "{{ main_repo_version }}"
      dest: "{{ main_repo_dest }}"
      update: yes
      force: no
    tags: ["main", "print_action"]

  - name: "update workspace repos"
    include_tasks: "repo.yml"
    loop: "{{ repos }}"  
    loop_control:
      loop_var: repo
      label: "{{ repo.name }}"
    tags: ["env", "other"]

  - name: "executable files"
    debug: 
      msg: "{{ repo_base_dest_workspace }}/{{ repo.local_repo }}/upgrade"
    loop: "{{ repos }}"  
    loop_control:
      loop_var: repo
      label: "{{ repo.name }}"
    tags: ["other", "print_action"]
