- name: Play 01 - Create and update the main and the environment repositories
  hosts: main
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 
    tags: ["main", "other"]

  - name: load environment vars
    include_vars:
      file: "env/vars.yml"
      name: env
    tags: ["main", "other"]
      
  - name: "update main repo (cloud)"
    git:
      repo: "{{ env.cloud_repo }}"
      version: "{{ env.cloud_repo_version }}"
      dest: "{{ (lookup('env', 'DEV') == '1') | ternary('/main/cloud', env.cloud_repo_dest) }}"
      update: "{{ (lookup('env', 'DEV') == '1') | ternary('no', 'yes') }}"
      force: "{{ (lookup('env', 'DEV') == '1') | ternary('no', 'yes') }}"
    tags: ["main", "print_action"]

  - name: "update workspace repos"
    include_tasks: "repo.yml"
    loop: "{{ env.repos }}"  
    loop_control:
      loop_var: repo
      label: "{{ repo.name }}"
    tags: ["env", "other"]

  - name: "executable files"
    debug: 
      msg: "{{ env.repo_base_dest_workspace }}/{{ repo.local_repo }}/upgrade"
    loop: "{{ env.repos }}"  
    loop_control:
      loop_var: repo
      label: "{{ repo.name }}"
    tags: ["other", "print_action"]
  
  - name: "{{ repo.name }} - update the repositories and directories permissions (dev)"
    command: "chown -R --reference=/root/ctl/ /main/"
    when: (lookup('env', 'DEV') == '1') and ((repo.env_dev_dir | default('')) != '')
    tags: ["never", "local"]
