- name: Play 01 - Create and update the main and the environment repositories
  hosts: main
  gather_facts: no  
  tasks: 
  - name: "[ctl] [main] gathering facts"
    setup: 
    tags: ["main", "other"]

  - name: "[ctl] [main]"
    include_tasks: "tasks/main_vars.yml"
    tags: ["main", "other"]

  - name: "[ctl] [main] update the workspace repos"
    include_tasks: "tasks/repo.yml"
    loop: "{{ env.repos }}"  
    loop_control:
      loop_var: repo
      label: "{{ repo.name }} ({{ repo.local_repo }})"
    when: ((env_repo_name | default('')) == '') or (env_repo_name == repo.local_repo)
    tags: ["env", "other"]

  - name: "[ctl] [main] run files of all repositories"
    template: 
      src: "{{ main_item.src }}"
      dest: "{{ main_item.dest }}"
      mode: 0755
    vars:
      repos: "{{ env.repos }}"
    loop: 
    - src: "templates/prepare-all.tpl.sh"
      dest: "/root/run/prepare-all.sh"
    - src: "templates/deploy-all.tpl.sh"
      dest: "/root/run/deploy-all.sh"
    loop_control:
      loop_var: main_item
      label: "{{ main_item.dest }}"
    when: (env_repo_name | default('')) == ''
    tags: ["other", "print_action"]
  
  - name: "[ctl] [main] update the repositories and directories permissions (dev)"
    command: "chown -R --reference=/root/ctl/ /main/"
    args:
      warn: false
    when: main_dev | bool
    tags: ["never", "local", "print_action"]
