- name: Play 01 - Prepare [{{ env_local_repo }}]
  hosts: main
  gather_facts: no  
  tasks:  

  - name: "[ctl] [prepare]"
    include_tasks: "tasks/main_vars.yml"
    tags: ["other"]

  - name: "[ctl] [prepare] [{{ env_local_repo }}]"
    set_fact: 
      repo: >-
        {{ 
        env.repos | selectattr('local_repo', 'equalto', env_local_repo) | first | default({}) 
        }}
    tags: ["other", "no_print"]

  - name: "[ctl] [prepare] - [{{ env_local_repo }}] fail - repo not found"
    fail:
      msg: "the repository was not found [{{ repo.name }}]"
    when: (repo.local_repo | default('')) == ''
    tags: ["other"]

  - name: "[ctl] [prepare] [{{ env_local_repo }}]"
    set_fact: 
      repo_title: "[ctl] [prepare] [{{ env_local_repo }}]"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }}"
    include_tasks: "tasks/repo_vars.yml"
    tags: ["other"]

  # repo env vars

  - name: "{{ repo_title }} - env"
    include_tasks: "tasks/env.yml"
    vars:
      repo_env_title: "{{ repo_title }} - env"
      repo_env_file: "{{ repo_env_dest }}/{{ repo.env_file }}"
      repo_env_ctx: ""
      repo_env_ctxs: "{{ repo.ctxs | default([]) }}"
      repo_env_dir: "{{ repo_env_dest }}"
      repo_env_ctl: true
      repo_env_main_dev: "{{ main_dev }}"
      repo_env_repo: "{{ repo }}"
      repo_env_repo_dest: "{{ repo_dest }}"
    tags: ["other"]

  # repo ctxs

  - name: "{{ repo_title }}"
    set_fact: 
      repo_env_aux: "{{ repo_env | combine({}) }}"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - copy the executable repo ctx files"
    include_tasks: "tasks/scripts.ctx.yml"
    vars:
      repo_env_inner: "{{ repo_env_aux | combine({ 'ctx': repo_item }) }}"
    loop: "{{ repo_env.ctxs }}"
    loop_control:
      loop_var: repo_item
    tags: ["other"]
      
  - name: "{{ repo_title }} - copy the main executable files"
    template:
      src: "templates/run.tpl.sh"
      dest: "{{ repo_dest }}/{{ repo_item }}"
      mode: 0700
    vars:
      repo_dir: "{{ repo_dest }}"
      repo_file: "{{ repo_item }}"
      repo_env_ctxs: "{{ repo_env.ctxs }}"
    loop:
    - "run"
    - "upgrade"
    loop_control:
      loop_var: repo_item
    tags: ["other"]

