- name: Play 01 - Prepare Context [{{ env_local_repo }}]
  hosts: main
  gather_facts: no  
  tasks:  

  - name: "[ctl - env] [prepare_ctx]"
    include_tasks: "tasks/main_vars.yml"
    tags: ["other"]

  - name: "{{ main_title }} [prepare_ctx] [{{ env_local_repo }}]"
    set_fact: 
      repo_title: "{{ main_title }} [prepare_ctx] [{{ env_local_repo }}] [ctx - {{ env_ctx }}]"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }}"
    set_fact: 
      repo: >-
        {{ 
        env.repos | selectattr('local_repo', 'equalto', env_local_repo) | first | default({}) 
        }}
    tags: ["other", "no_print"]

  - name: "{{ repo_title }}"
    include_tasks: "tasks/repo_vars.yml"
    tags: ["other"]

  # repo env vars

  - name: "{{ repo_title }} - env"
    include_tasks: "tasks/env.yml"
    vars:
      repo_env_title: "{{ repo_title }} - env"
      repo_env_file: "{{ env_dir }}/{{ repo.env_file }}"
      repo_env_dir: "{{ env_dir }}"
      repo_env_ctx: ""
      repo_env_ctxs: "{{ repo.ctxs | default([]) }}"
      repo_env_ctl: true
      repo_env_main_dev: "{{ main_dev }}"
      repo_env_repo: "{{ repo }}"
      repo_env_repo_dest: "{{ repo_dest }}"
    tags: ["other"]

  # repo ctxs

  - name: "{{ repo_title }}"
    set_fact: 
      repo_env_aux: "{{ repo_env | combine({}) }}"
    tags: ["other", "no_print"]

  - name: "{{ repo_title }} - copy the executable ctx files"
    include_tasks: "tasks/repo.ctx.yml"
    vars:
      repo_env_inner: "{{ repo_env_aux | combine({ 'ctx': env_ctx }) }}"
    tags: ["other"]
