- name: "{{ repo_inner_title }}"
  set_fact:
    repo_env_main: "{{ repo_env_inner.main[repo_env_inner.ctx] }}"
  tags: ["other", "no_print"]

- name: "{{ repo_inner_title }}"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: "{{ repo_env_main.params | default({}) }}"
    params_mixer_group_params_names: "{{ repo_env_main.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ repo_env_main.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ repo_env_main.shared_group_params | default('') }}"
    params_mixer_shared_params_names_dict: "{{ repo_env_inner.main_shared_params | default({}) }}"
    params_mixer_shared_group_params_names_dict: "{{ repo_env_inner.main_shared_group_params | default({}) }}"
    params_mixer_params_dict: "{{ repo_env_inner.main_params | default({}) }}"
  tags: ["other", "no_print"]

- name: "{{ repo_inner_title }}"
  set_fact:
    repo_env_main_params: "{{ params_mixer_params }}"
  tags: ["other", "no_print"]