- name: "{{ template_title }} - create the template directories (tmp and final)"
  become: "{{ template_become | default('no') }}"
  file:
    path: "{{ template_item }}"
    state: directory
    mode: 0755
  loop: 
  - "{{ template_tmp_dest | dirname }}"
  - "{{ template_dest | dirname }}"
  loop_control:
    loop_var: template_item
  tags: "{{ template_task_tags }}"

- name: "{{ template_title }}"
  set_fact:
    template_params_final: "{{ template_params | default({}) | combine({}) }}"
    template_meta_final: "{{ template_meta | default({}) | combine({}) }}"
    template_ctl_params_final: "{{ template_ctl_params | default({}) | combine({}) }}"
    template_local_params_final: "{{ template_local_params | default({}) | combine({}) }}"
  tags: "{{ (template_task_tags | default([])) + ['no_print'] }}"

- name: >-
    {{ template_title }} - 
    transfer the template to the specified tmp location
    ({{ template_src }} to {{ template_tmp_dest }})
  become: "{{ template_become | default('no') }}"
  template: 
    src: "{{ template_src }}"
    dest: "{{ template_tmp_dest }}"
    owner: "{{ template_owner | default(omit, true) }}"
    group: "{{ template_group | default(omit, true) }}"
    mode: >-
      {{ 
      template_mode | default(
      ((template_local | default('')) == 'local') | ternary(0666, omit), true) 
      }}
    block_end_string: "%>"
    block_start_string: "<%"
    variable_end_string: ">>"
    variable_start_string: "<<"
  vars:
    params: "<< template_params_final >>"
    meta_params: "<< template_meta_final >>"
    env_params: "<< template_ctl_params_final >>"
    local_params: "<< template_local_params_final >>"
  changed_when: false
  tags: "{{ template_task_tags }}"

- name: "{{ template_title }}"
  set_fact:
    template_regex: "^\\s*$"
  tags: "{{ (template_task_tags | default([])) + ['no_print'] }}"

- name: "{{ template_title }}"
  set_fact:
    template_regex: "\\n\\s*$"
  when: template_meta.template_no_empty_lines | default(false) | bool
  tags: "{{ (template_task_tags | default([])) + ['no_print'] }}"

- name: >-
    {{ template_title }} -
    remove excess of blank lines of the file created from the template
    ({{ template_tmp_dest }})
  replace:
    path: "{{ template_tmp_dest }}"
    regexp: "{{ template_regex }}"
    replace: ""
  changed_when: false
  tags: "{{ template_task_tags }}"

- name: >-
    {{ template_title }} -
    copy the normalized file created from the template to the specified location
    ({{ template_dest }})
  become: "{{ template_become | default('no') }}"
  copy:
    remote_src: "{{ template_remote_src | default('false') }}"
    src: "{{ template_tmp_dest }}"
    dest: "{{ template_dest }}"
    owner: "{{ template_owner | default(omit) }}"
    group: "{{ template_group | default(omit) }}"
    mode: >-
      {{ 
      template_mode | default(template_local | default(false) | bool | ternary(0666, omit), true) 
      }}
  tags: "{{ template_task_tags }}"